SELECT * FROM price_list

DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
GRANT ALL ON SCHEMA public TO public;


CREATE TABLE region (
	region_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(32) NOT NULL UNIQUE,
	description TEXT
);

CREATE TABLE city (
	city_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	region_id INT NOT NULL,
	name VARCHAR(32) NOT NULL,
	description TEXT,
	
	CONSTRAINT fk_city_region
		FOREIGN KEY (region_id)
		REFERENCES region(region_id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);

CREATE TABLE district (
	district_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	city_id INT NOT NULL,
	name VARCHAR(32) NOT NULL,
	
	CONSTRAINT fk_district_city
		FOREIGN KEY (city_id)
		REFERENCES city(city_id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);

CREATE TABLE parking (
	parking_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	district_id INT NOT NULL,
	coords POINT,
	
	CONSTRAINT fk_parking_district
		FOREIGN KEY (district_id)
		REFERENCES district(district_id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);



CREATE TABLE car_class (
	car_class_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name CHAR(7) CHECK (name in ('econom', 'middle', 'premium', 'family')),
	description TEXT
);

CREATE TABLE price_list (
	car_class_id INT,
	region_id INT,
	cost_min NUMERIC(6,2) CHECK (cost_min >= 0),
	cost_hour NUMERIC(6,2) CHECK (cost_hour >= 0),
	
	CONSTRAINT pk_price_list PRIMARY KEY (car_class_id, region_id),
	
	CONSTRAINT fk_price_list_car_class
		FOREIGN KEY (car_class_id)
		REFERENCES car_class(car_class_id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
		
	CONSTRAINT fk_price_list_region
		FOREIGN KEY (region_id)
		REFERENCES region(region_id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);

CREATE TABLE car (
	car_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	class_id INT NOT NULL,
	region_id INT NOT NULL,
	number VARCHAR(32) NOT NULL UNIQUE,
    brand VARCHAR(32) NOT NULL,
    model VARCHAR(32) NOT NULL,
    color VARCHAR(32),
    capacity SMALLINT NOT NULL CHECK (capacity >= 1),
    engine_volume NUMERIC(3,1) CHECK (engine_volume >= 0),
    fuel_consumption NUMERIC(3,1),

    CONSTRAINT fk_car_class
        FOREIGN KEY (class_id)
        REFERENCES car_class (car_class_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT fk_car_region
        FOREIGN KEY (region_id)
        REFERENCES region (region_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

CREATE TABLE visit_sc (
	visit_sc_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	car_id INT NOT NULL,
	begin_date DATE NOT NULL,
	end_date DATE CHECK (end_date IS NULL OR end_date >= begin_date),
	cause TEXT,
	status TEXT NOT NULL CHECK (status in ('planned', 'in_progress', 'done', 'cancelled')),
	total_cost NUMERIC(11,2),
	
    CONSTRAINT fk_visit_sc_car
        FOREIGN KEY (car_id)
        REFERENCES car (car_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE sc (
	sc_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	district_id INT NOT NULL,
	name VARCHAR(32) NOT NULL,
	address TEXT,
	
	CONSTRAINT fk_sc_district
		FOREIGN KEY (district_id)
		REFERENCES district(district_id)
		ON DELETE RESTRICT
		ON UPDATE CASCADE
);

CREATE TABLE service (
    service_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(32) NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE service_sc (
	service_sc_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sc_id INT NOT NULL,
    service_id INT NOT NULL,
    cost NUMERIC(11,2) CHECK (cost IS NULL OR cost >= 0),

    CONSTRAINT fk_service_sc_sc
        FOREIGN KEY (sc_id)
        REFERENCES sc (sc_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_service_sc_service
        FOREIGN KEY (service_id)
        REFERENCES service (service_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE visit_sc_per_service_sc (
	visit_sc_id INT,
	service_sc_id INT,
	info TEXT,

	CONSTRAINT pk_visit_sc_per_service_sc
		PRIMARY KEY (visit_sc_id, service_sc_id),

	CONSTRAINT fk_visit_sc_per_service_sc_visit_sc
		FOREIGN KEY (visit_sc_id)
		REFERENCES visit_sc (visit_sc_id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,

	CONSTRAINT fk_visit_sc_per_service_sc_service_sc
		FOREIGN KEY (service_sc_id)
		REFERENCES service_sc (service_sc_id)
		ON DELETE RESTRICT
		ON UPDATE RESTRICT
)


CREATE TABLE maintenance_info (
    info_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_id INT NOT NULL,
    visit_sc_id INT NOT NULL,
    date DATE,

    CONSTRAINT fk_maintenance_info_car
        FOREIGN KEY (car_id)
        REFERENCES car (car_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_maintenance_info_visit_sc
        FOREIGN KEY (visit_sc_id)
        REFERENCES visit_sc (visit_sc_id)
        ON DELETE RESTRICT
        ON UPDATE RESTRICT
);



--- то, что связано с аккаунтами

CREATE TABLE role (
	role_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name VARCHAR(32) CHECK (name in('renter', 'employee', 'administration')),
	descriprion TEXT
);

CREATE TABLE account (
	account_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	role_id INT NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	password_hash CHAR(32) NOT NULL,

	CONSTRAINT fk_account_role
		FOREIGN KEY (role_id)
		REFERENCES role (role_id)
		ON DELETE RESTRICT
		ON UPDATE CASCADE
	
);

CREATE TABLE action (
	action_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	account_id INT NOT NULL,
	type CHAR(6) CHECK (type in('delete', 'update', 'insert')),
	old_value TEXT,
	new_value TEXT,

	CONSTRAINT fk_action_account
		FOREIGN KEY (account_id)
		REFERENCES account (account_id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);


CREATE TABLE employee (
    employee_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INT NOT NULL,
    full_name TEXT NOT NULL,
    phone VARCHAR(32) NOT NULL,
    passport_series CHAR(4) NOT NULL,
    passport_number CHAR(6) NOT NULL,
    birth_date DATE,

    CONSTRAINT fk_employee_account
        FOREIGN KEY (account_id)
        REFERENCES account (account_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE renter (
    renter_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INT NOT NULL,
    full_name TEXT NOT NULL,
    phone VARCHAR(32) NOT NULL,
    passport_series CHAR(4) NOT NULL,
    passport_number CHAR(6) NOT NULL,
    birth_date DATE NOT NULL,
    driver_license_date DATE NOT NULL,
    license_ack BOOLEAN,

    CONSTRAINT fk_renter_account
        FOREIGN KEY (account_id)
        REFERENCES account (account_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE booking (
    booking_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_id INT NOT NULL,
    renter_id INT NOT NULL,
    begin_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP CHECK (end_time IS NULL OR end_time >= begin_time),
    type VARCHAR(32) CHECK (type in ('mins', 'hours')),

    CONSTRAINT fk_booking_car
        FOREIGN KEY (car_id)
        REFERENCES car (car_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT fk_booking_renter
        FOREIGN KEY (renter_id)
        REFERENCES renter (renter_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE

);


CREATE TABLE gps (
    gps_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_id INT NOT NULL,
    booking_id INT NOT NULL,
    coords POINT,

    CONSTRAINT fk_gps_car
        FOREIGN KEY (car_id)
        REFERENCES car (car_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_gps_booking
        FOREIGN KEY (booking_id)
        REFERENCES booking (booking_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


CREATE TABLE card (
    card_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    renter_id INT NOT NULL,
    payment_token TEXT NOT NULL,
    last_digits CHAR(4) NOT NULL,
    duration DATE NOT NULL,
    payment_system VARCHAR(32),

    CONSTRAINT fk_card_renter
        FOREIGN KEY (renter_id)
        REFERENCES renter (renter_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE fine (
    fine_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    renter_id INT NOT NULL,
    booking_id INT NOT NULL,
    cause TEXT NOT NULL,
    receiving_time TIMESTAMP NOT NULL,
    payment_time TIMESTAMP,
    amount NUMERIC(11,2) NOT NULL,

    CONSTRAINT fk_fine_renter
        FOREIGN KEY (renter_id)
        REFERENCES renter (renter_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT fk_fine_booking
        FOREIGN KEY (booking_id)
        REFERENCES booking (booking_id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT chk_fine_amount
        CHECK (amount IS NULL OR amount >= 0),

    CONSTRAINT chk_fine_times
        CHECK (payment_time IS NULL OR payment_time >= receiving_time)
);


CREATE TABLE debiting (
    debiting_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id INT NOT NULL,
    booking_id INT NOT NULL,
    time_interval INTERVAL NOT NULL,
    amount NUMERIC NOT NULL,
    type CHAR(4) CHECK (type in ('fine', 'min', 'hour')),

    CONSTRAINT fk_debiting_card
        FOREIGN KEY (card_id)
        REFERENCES card (card_id)
        ON DELETE SET NULL
        ON UPDATE CASCADE,

    CONSTRAINT fk_debiting_booking
        FOREIGN KEY (booking_id)
        REFERENCES booking (booking_id)
        ON DELETE RESTRICT
        ON UPDATE CASCADE,

    CONSTRAINT chk_debiting_amount
        CHECK (amount >= 0)
);


